jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set API Key as Environment Variable
        env:
          API_KEY: ${{ secrets.CHATGPT_API_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Use API Key in Script
        run: |
          # Access the secret API key as an environment variable
          echo "API Key: $API_KEY"

          # You can use $API_KEY in your JavaScript script
          node your-script.js
